- name: Docker is present
  yum:
    name: docker-engine
    state: latest
    force: yes
    tags: [docker]

- name: Pull jenkins image
  command: "/usr/bin/docker pull jenkins/5000:jenkao_get"

- name: Add jenkins container
  docker:
    name: jenkins
    image: "jenkins/5000:jenkao"
    state: reloaded
    ports: "127.0.0.1:8000:8000"
    restart_policy: always
    env: "jenkins"
